#!/usr/bin/env python
# --------------------------------------------------------------------------------------------------------- Intermediate
def sigmoid(x):
	return 1 / (1 + math.exp(-x))

def sigmoid(x):
	x2 = -1.0*x
	a = math.exp(x2)
	nominator = 1
	denominator = 1 + a
	return nominator / denominator
# --------------------------------------------------------------------------------------------------------- Advanced
import math
import numpy as np

x = np.array([4, 3, 0])
c1 = np.array([-.5, .1, .08])
c2 = np.array([-.2, .2, .31])
c3 = np.array([.5, -.1, 2.53])

def sigmoid(z):
    return sum(z)

print(sigmoid(x))
print(sigmoid(c1))
print(sigmoid(c2))
print(sigmoid(c3))
