#!/usr/bin/env python
# --------------------------------------------------------------------------------------------------------- Intermediate
import random

def main():
    prob = 0.80
    if random.random() < prob:
        print('dog')
    else:
        print('cat')

main()
# --------------------------------------------------------------------------------------------------------- Advanced
import random

def main():
    # if random.random() < 0.1:
    #     favourite = "bats"
    #     print("I love " + favourite)  
    if random.random() < 0.8:
        favourite = "dogs"
        print("I love " + favourite) 
    if random.random() < 0.1:
        favourite = "cats"
        print("I love " + favourite) 
    if random.random() < 0.1:
        favourite = "bats"
        print("I love " + favourite) 
main()
